/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crearleerxml;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author SADValenz
 */
public class menuXML extends javax.swing.JFrame {
    metodos metodosXML= new metodos();
    short posicion=0;
    
    /**
     * Creates new form menuXML
     */
    boolean accion;
    public menuXML() {
        initComponents();
        metodosXML.comprobarExistencia();
        textTsbla.setText(metodosXML.mostrar());
        
        if(metodosXML.vacio()==false){
        botonEliminar.setEnabled(true);
        botonCambiar.setEnabled(true);
        if(metodosXML.arrayAux.size()>1){
        botonAnterior.setEnabled(true);
        botonSiguiente.setEnabled(true);
        }
        visualizar(posicion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textTsbla = new javax.swing.JTextArea();
        botonAgregar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonCambiar = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonAnterior = new javax.swing.JButton();
        botonSiguiente = new javax.swing.JButton();
        textNControl = new javax.swing.JTextField();
        textNombres = new javax.swing.JTextField();
        textApellidos = new javax.swing.JTextField();
        textCarrera = new javax.swing.JTextField();
        botonListo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Practica 7 XML");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Num. Control");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Carrera");

        textTsbla.setColumns(20);
        textTsbla.setRows(5);
        textTsbla.setEnabled(false);
        jScrollPane1.setViewportView(textTsbla);

        botonAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAgregar.setText("Agregar");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        botonCambiar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonCambiar.setText("Cambiar");
        botonCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCambiarActionPerformed(evt);
            }
        });

        botonGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonAnterior.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonAnterior.setText("Anterior");
        botonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAnteriorActionPerformed(evt);
            }
        });

        botonSiguiente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonSiguiente.setText("Siguiente");
        botonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSiguienteActionPerformed(evt);
            }
        });

        textNControl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textNControl.setEnabled(false);

        textNombres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textNombres.setEnabled(false);

        textApellidos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textApellidos.setEnabled(false);

        textCarrera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        textCarrera.setEnabled(false);

        botonListo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        botonListo.setText("Listo");
        botonListo.setEnabled(false);
        botonListo.setFocusPainted(false);
        botonListo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonAgregar)
                                    .addComponent(botonCambiar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEliminar)
                                    .addComponent(botonGuardar))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonAnterior)
                                        .addGap(18, 18, 18)
                                        .addComponent(botonSiguiente)
                                        .addGap(80, 207, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(textApellidos)
                                            .addComponent(textNombres)
                                            .addComponent(textCarrera))
                                        .addGap(8, 8, 8)
                                        .addComponent(botonListo)
                                        .addGap(38, 38, 38))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(textNControl, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(textApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonListo)
                        .addGap(36, 36, 36)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAnterior)
                    .addComponent(botonSiguiente))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonAgregar)
                            .addComponent(botonEliminar))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCambiar)
                            .addComponent(botonGuardar))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        textApellidos.setText("");
        textNControl.setText("");
        textCarrera.setText("");
        textNombres.setText("");
        
        prepararCambio();
        
        accion=true;
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonListoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListoActionPerformed
        if(accion){
            agregar();
        }else{
            cambiar();
        }
        
        
        botonAgregar.setEnabled(true);
        botonAnterior.setEnabled(true);
        botonCambiar.setEnabled(true);
        botonEliminar.setEnabled(true);
        botonGuardar.setEnabled(true);
        botonSiguiente.setEnabled(true);

        
        textNControl.setEnabled(false);
        textApellidos.setEnabled(false);
        textCarrera.setEnabled(false);
        textNombres.setEnabled(false);
        
        botonListo.setEnabled(false);
        textTsbla.setText(metodosXML.mostrar());
    }//GEN-LAST:event_botonListoActionPerformed

    private void botonCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCambiarActionPerformed
       prepararCambio();
       
       accion=false;
       
       textTsbla.setText(metodosXML.mostrar());
    }//GEN-LAST:event_botonCambiarActionPerformed

    private void botonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSiguienteActionPerformed
        posicion++;
        if(posicion>=metodosXML.arrayAux.size()){
        posicion=0;
        }
        visualizar(posicion);
    }//GEN-LAST:event_botonSiguienteActionPerformed

    private void botonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAnteriorActionPerformed
         posicion--;
        if(posicion<0){
        posicion=(short) (metodosXML.arrayAux.size()-1);
        }
        visualizar(posicion);
    }//GEN-LAST:event_botonAnteriorActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        try {
            metodosXML.guardar();
        } catch (IOException ex) {
            Logger.getLogger(menuXML.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        metodosXML.quitar(posicion);
        if(metodosXML.arrayAux.size()>1){
        posicion-=1;
        visualizar(posicion);
        }
        else{
        textApellidos.setText("");
        textNControl.setText("");
        textCarrera.setText("");
        textNombres.setText("");
        
        botonSiguiente.setEnabled(false);
        botonAnterior.setEnabled(false);
        botonEliminar.setEnabled(false);
        }
        textTsbla.setText(metodosXML.mostrar());
    }//GEN-LAST:event_botonEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuXML().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonCambiar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonListo;
    private javax.swing.JButton botonSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textCarrera;
    private javax.swing.JTextField textNControl;
    private javax.swing.JTextField textNombres;
    private javax.swing.JTextArea textTsbla;
    // End of variables declaration//GEN-END:variables

    private void agregar() {
       Usuario alumno= new Usuario(textNControl.getText(), textNombres.getText(), textApellidos.getText(), textCarrera.getText());
        metodosXML.agregar(alumno);
        posicion=(short) (metodosXML.arrayAux.size()-1);
        botonEliminar.setEnabled(false);
    }

    private void cambiar() {
        Usuario alumno= new Usuario(textNControl.getText(), textNombres.getText(), textApellidos.getText(), textCarrera.getText());
        metodosXML.cambiar(posicion,alumno);
    }

    private void prepararCambio() {
        textNControl.setEnabled(true);
        textApellidos.setEnabled(true);
        textCarrera.setEnabled(true);
        textNombres.setEnabled(true);
        
 
        botonAgregar.setEnabled(false);
        botonAnterior.setEnabled(false);
        botonCambiar.setEnabled(false);
        botonEliminar.setEnabled(false);
        botonGuardar.setEnabled(false);
        botonSiguiente.setEnabled(false);

        
        botonListo.setEnabled(true);
    }

    private void visualizar(short pos) {
        Usuario alumno=metodosXML.visualizar(pos);
        
        textNControl.setText(alumno.getNumControl());
        textApellidos.setText(alumno.getApellidos());
        textCarrera.setText(alumno.getCarrera());
        textNombres.setText(alumno.getNombres());
   }
}
